name: Crystal CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: shards install --ignore-crystal-version
    - name: Run tests
      run: crystal spec
    - name: Build docs
      run: crystal docs
    - uses: peaceiris/actions-gh-pages@v3
      if: github.event_name == 'push'
      with:
        github_token: ${{ secrets.DOCS_TOKEN }}
        publish_dir: ./docs
